# add defaults here with the namespace key and then the actual key
# only comes in effect, when no value and no fallback are given
#

# angebots und auftragsnummer optional
# @todo Korrekturrechnung
# Kundennummer als Pflichtfeld markieren
# @todo rechnungsnummer
# info an buchhaltung@, wenn neue Kundennumer vergeben wurde
# Untertitel erstmal raus
# Angebot nicht oben rechts
# Ersteller oben rechts automatisch aus dem System
#  Ersteller feld sperren --> Hier kommt der der Fertigstellt
# Pflichtfelder
# * Leistungszeitraum
# * Angaen Kunde
#* Kunde seite komplett sperren
# UStId des Kunden als Label in Kunde
# Zusatztext. Generell raus
# Menge als Decimal mit 2 Nahckommastellen
# ME -> 1: Anzahl, 2: Stunden, 3: Pauschal, 4: Optional
# Einheiten werden in Zusatztext nach der Rechnung erklärt
#*  ME = Mengeneinheit (1 - pauschal, 2 - Anzahl, 3 - optional)
#▪ ME = Mengeneinheit (1 - pauschal, 2 - Anzahl, 3 - optional)
#▪ wir empfehlen ihnen den Abschluss eines Servicevertrages
# Einzelpreis bekommt schalter für verstecken
# CRM.Kunde
# - keine Kundennumer, wenn die die UstId fehlt
# - SafeGuar, wenn UstId beim Kunden fehlt, fehler werfen
# - ist bezahlt als schalter

# Rechnung bezahlt - ja / nein
# Zusatztext für Zahlungsbedingungen in der Registry mit definieren
# Zahlungsbedingungen mit in den Kunden rein --> auch Sepa beachten

# Zahlungsbedingungen
#
#   Ziffer 1	Der Rechnungsbetrag (Brutto) ist zahlbar innerhalb von 14 Kalendertagen nach dem ausgewiesenen Rechnungsdatum.
#   Ziffer 2	Sepa Mandat
#   Ziffer 3	freitext?
#   Damit infos aus Auftrag nehmen

# Konto im Kundenstamm für Sepa Lastschriftmandat
# Texte in den Dauerrechnungen Bankverbindung etc.

# ab 01.01. eRechnung an LV und Bilddungswerk und DRK Service

# Zwischenschritt vor der Freigabe der Rechnung einführen

fucodo:
  registry:
    defaults:
      KayStrobach_Invoice_General:
        items:
          fluidInvoiceTemplateRootPaths:
            type: Text
            label: Template file to be used for the invoices
            default: 'resource://KayStrobach.Invoice/Private/Documents/'
            description:
          fluidInvoicePartialRootPaths:
            type: Text
            label: Template file to be used for the invoices
            default: 'resource://KayStrobach.Invoice/Private/Partials/'
            description:
          fluidInvoiceLayoutRootPaths:
            type: Text
            label: Template file to be used for the invoices
            default: 'resource://KayStrobach.Invoice/Private/Layouts/'
            description:
          invoiceSeries:
            type: Textarea
            label: Rechnungskreise (Achtung, braucht JSON als Input)
            default: 'Default,RecurringBilling,StornoBilling'
            description:
          stornoSeries:
            type: Textarea
            label: StornoRechnungseinstellungen
            default: 'StornoBilling'
            description:
