fucodo:
  registry:
    defaults:
      KayStrobach_Invoice_InvoiceSettings_RecurringBilling:
        items:
          ################################################################################################################
          # General Invoice defaults
          #################################################################################################################
          numberPrefix:
            type: Text
            label:
            default: 'DR-%year-'
            description:
          numberPostfix:
            type: Text
            label:
            default: ''
            description:
          title:
            type: Text
            label:
            default: Dauerrechnung
            description:
          subTitle:
            type: Text
            label:
            default: ""
            description:
          additionalInformation:
            type: Textarea
            label:
            default: |
              @todo Anpassen mit der Vertragsart etc.

              Diese Rechnung gilt ab 01.01.-31.12.2025,
              entsprechend dem Auftrag {invoice.order.orderNumber} vom {invoice.order.commissioningDate} und den Allgemeinen
              Gesch채ftsbedingungen (Stand: Oktober 2024).
              Die G체ltigkeit erlischt, ab dem die vorliegende Rechnung durch eine neu ausgestellte
              Rechnung ersetzt wird oder wenn das Vertragsverh채ltnis beendet wird.

              Leistungszeitraum monatlich
            description:
          paymentTermText:
            type: TextArea
            label: Zahlungsbedingungen
            default: |
              Der Rechnungsbetrag (Brutto) ist zahlbar innerhalb von 14 Kalendertagen nach dem ausgewiesenen Rechnungsdatum.

              Wie mit Ihnen vereinbart, werden wir den obigen Rechnungsbetrag (Brutto) innerhalb der n채chsten 3 Werktage von der uns benannten Bankverbindung einziehen.
